Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [7]:
import numpy as np

n = int(input('Введите число: '))

np.arange(0, n)[::-1]

Введите число: 5


array([4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [13]:
n = int(input('Введите число: '))

matrix = np.diag(np.arange(0, n)[::-1])
print(matrix)
np.sum(matrix)

#или

sum_matrix = 0
for i in range(n):
    sum_matrix += matrix[i][i]

sum_matrix

Введите число: 5
[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]


10

Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [20]:
from numpy import linalg

a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

print(linalg.solve(a, b))

np.dot(a, linalg.solve(a, b))

[ 0.46666667  3.84444444 -5.55555556]


array([ 4., 12., -3.])